# Generated by Django 5.1 on 2024-08-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('hallticket_no', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.TextField(default=None, max_length=250)),
                ('year', models.TextField(default=None, max_length=250)),
                ('branch', models.TextField(default=None, max_length=250)),
            ],
        ),
    ]
