# Generated by Django 5.1 on 2024-08-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='hallticket_no',
            field=models.TextField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
