# Generated by Django 5.1 on 2024-08-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_student_branch_alter_student_hallticket_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(max_length=100)),
                ('job_description', models.TextField(max_length=1000)),
                ('job_location', models.TextField(max_length=100)),
                ('job_salary', models.TextField(max_length=100)),
                ('job_type', models.TextField(max_length=100)),
            ],
        ),
    ]
